#!/usr/bin/env python3
# -*- coding: utf-8 -*-
"""
Created on Thu Jun  7 11:17:01 2018

@author: shirlaen
"""
import pyjapc
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt

japc = pyjapc.PyJapc(incaAcceleratorName="LEIR",
                     noSet=True)
japc.setSelector("LEI.USER.NOMINAL")

acquisition =japc.getParam("LEI.BQS.L/Acquisition")
settings = japc.getParam("LEI.BQS.L/Setting")