#!/usr/bin/env python3
# -*- coding: utf-8 -*-
"""
Created on Wed May 23 09:21:34 2018

@author: shirlaen
"""

from PyQt5.QtWidgets import QMainWindow, QMessageBox
from PyQt5.QtGui import *
from PyQt5.QtWidgets import *
from PyQt5.QtCore import *
from PyQt5.QtCore import QThread, pyqtSignal


import numpy as np
import pyjapc
import ParameterClass as pc
import ObservableClass as ob
import GetOptimalMultiValueThreadClass as gOVThread
from sceleton import Ui_MainWindow



japc = pyjapc.PyJapc(incaAcceleratorName="LEIR", noSet=False)
japc.setSelector("LEI.USER.EARLY")

averageNrValue = 5.
parameterClass = pc.ParameterClass(japc)


ob = ob.ObservableClass(5)
getOptimalValueThread = gOVThread.getOptimalMultiValueThread(
                    parameterClass, ob)