#!/usr/bin/env python3
# -*- coding: utf-8 -*-
"""
Created on Fri Jun  1 10:09:47 2018

@author: shirlaen
"""

import pyjapc

name = "rmi://virtual_leir/logical.ITH.DHZ10/K#value"
japc = pyjapc.PyJapc(incaAcceleratorName="LEIR", noSet=False)
japc.setSelector("LEI.USER.EARLY")

def getValue():
    knobParam = japc.getParam(name, noPyConversion=True,
                              timingSelectorOverride=
                              japc.getSelector()).getValue()
    returnValue = knobParam.double
    return returnValue

def setValue(x):
    knobParam = japc.getParam(name, noPyConversion=True,
                              timingSelectorOverride=
                              japc.getSelector()).getValue()
    knobParam.double = x
    print()
    japc.setParam(name, knobParam)
    return None


print(getValue())
setValue(getValue())


